---
# handlers file for linux

- name: Update apt cache
  become: yes
  apt:
    cache_valid_time: 3600  # Cache valid for 1 hour to avoid frequent updates

- name: reload ufw
  ufw:
    state: reloaded
  when: ufw_state == 'enabled'