## Docker Repository Setup
# Managed by Ansible
# Adds the Docker repository Docker CE (Community Edition)

- name: Install Docker Public Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify:
    - Update apt cache

- name: Add Docker Repo
  become: True
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: 'docker-ce'
    state: present
    update_cache: yes
  notify:
    - Update apt cache