## Docker Repository Setup
# Managed by Ansible
# Adds the Docker repository Docker CE (Community Edition)

- name: Download Docker GPG Key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker Repo
  become: True
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: 'docker-ce'
    state: present
    update_cache: yes
  notify:
    - Update apt cache