## Google Repositories Setup
# Managed by Ansible
# Adds Google Chrome and Google Earth repositories

- name: Install Google Public Key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  notify:
    - Update apt cache

- name: Add Google Chrome Repo
  become: True
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: 'google-chrome-stable'
    state: present
    update_cache: yes
  notify:
    - Update apt cache

- name: Add Google Earth Repo
  become: True
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main
    filename: 'google-earth-stable'
    state: present
    update_cache: yes
  notify:
    - Update apt cache
