## Google Repositories Setup
# Managed by Ansible
# Adds Google Chrome and Google Earth repositories

- name: Download Google Chrome GPG Key
  become: true
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google.asc
    mode: '0644'

- name: Add Google Chrome repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.asc] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: 'google'
    state: present
  notify:
    - Update apt cache

- name: Add Google Earth Repo
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google.asc] http://dl.google.com/linux/earth/deb/ stable main
    filename: 'google'
    state: present
  notify:
    - Update apt cache
