## Microsoft Repo Setup
# Managed by Ansible
# Adds the Microsoft repository for Visual Studio Code and other Microsoft packages

- name: Download Microsoft GPG Key
  become: true
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'

- name: Add Microsoft repository for VS Code
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main"
    filename: 'microsoft'
    state: present
  notify:
    - Update apt cache

- name: Add Microsoft repository for Teams
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/ms-teams stable main"
    filename: 'microsoft'
    state: present
  notify:
    - Update apt cache
