## VirtualBox Repository Setup
# Managed by Ansible
# Adds the VirtualBox repository and installs VirtualBox

- name: Install VirtualBox Public Key
  apt_key:
    url: https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
    state: present
  notify:
    - Update apt cache

- name: Add VirtualBox Repo
  become: True
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    filename: 'virtualbox'
    state: present
    update_cache: yes
  notify:
    - Update apt cache