## Vivaldi Browser Repo Setup
# Managed by Ansible
# Adds the Vivaldi browser repository

- name: Download Vivaldi GPG Key
  get_url:
    url: https://repo.vivaldi.com/stable/linux_signing_key.pub
    dest: /etc/apt/keyrings/vivaldi.asc
    mode: '0644'

- name: Add Vivaldi repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/vivaldi.asc] http://repo.vivaldi.com/stable/deb stable main"
    filename: 'vivaldi'
    state: present
  notify:
    - Update apt cache