## Vivaldi Browser Repo Setup
# Managed by Ansible
# Adds the Vivaldi browser repository

- name: Install Vivaldi Public Key
  apt_key:
    url: http://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  notify:
    - Update apt cache

- name: Add Vivaldi Repo
  become: True
  apt_repository:
    repo: deb http://repo.vivaldi.com/stable/deb/ stable main
    filename: 'vivaldi-stable'
    state: present
    update_cache: yes
  notify:
    - Update apt cache