- name: Install common system applications
  hosts: localhost
  roles:
    - common
    - { role: linux, when: ansible_os_family == "Debian" or ansible_os_family == "RedHat" }
    - { role: mac, when: ansible_os_family == "Darwin" }
