---
- name: Ensure the system is updated
  ansible.builtin.command: "{{ item }}"
  loop:
    - "echo 'Updating system...'"

- name: Deploy Git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    mode: '0644'
