---
- name: Ensure the system is updated
  ansible.builtin.command: "{{ item }}"
  loop:
    - "echo 'Updating system...'"

- name: Deploy Git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: >-
      {% if ansible_os_family == 'Linux' %}
        /home/{{ ansible_user }}/.gitconfig
      {% elif ansible_os_family == 'Darwin' %}
        /Users/{{ ansible_user }}/.gitconfig
      {% endif %}
    owner: "{{ ansible_user }}"
    mode: '0644'
