---
# tasks file for mac
- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: brew_check
  ignore_errors: yes

- name: Install Homebrew if missing
  ansible.builtin.shell: "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
  when: brew_check.rc != 0

- name: Install htop and git using Homebrew
  community.general.homebrew:
    name:
      - htop
      - git
      - ansible
      - exiftool
      - awscli
      - ca-certificates
      - irssi
      - xz
      - curl
      - curl-openssl
      - openvpn
    state: present

- name: Add the Homebrew tap for Ferdium
  community.general.homebrew_tap:
    name: ferdium/ferdium
    state: present

- name: Install applications using Homebrew Cask
  community.general.homebrew_cask:
    name:
      - android-studio
      - balenaetcher
      - chromium
      - cisco-packet-tracer
      - darktable
      - deezer
      - docker
      - ferdium
      - filezilla
      - firefox
      - flutter
      - freecad
      - gimp
      - google-chrome
      - google-drive
      - istat-menus
      - libreoffice
      - musescore
      - openvpn-connect
      - rawtherapee
      - sketchup
      - slack
      - telegram
      - thunderbird
      - tor-browser
      - tunnelblick
      - vlc
      - visual-studio-code
      - whatsapp
      - android-platform-tools
      - firebase-cli
      - xcode
    state: present

# Synology Drive Client Installation (manual)
- name: Display a message for manual installation
  debug:
    msg: |
      Please download and manually install Synology Drive Client from:
      https://www.synology.com/fr-fr/support/download
      Family Tree Builder 
      FreeTube
